version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    restart: always
    ports:
      - 8052:8052
    depends_on:
      - db